#!/bin/sh
# Build an isolated, complete SDK installation from the pinned source checkouts.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

while [ "$#" -gt 0 ]
do
    case "$1" in
        --build-dir)
            sdk_root=$2
            shift 2
            ;;

        --variant)
            variant=$2
            shift 2
            ;;

        --built-marker)
            built_marker=$2
            shift 2
            ;;

        *)
            printf 'Unknown option: %s\n' "$1" >&2
            exit 1
            ;;
    esac
done

install_root="$sdk_root/$variant"

mkdir -p "$install_root"
rm -f "$built_marker"

# Copy committed SDK and ports sources into a temporary directory, excluding
# Git metadata and local changes. Apply patches and compile there to leave the
# submodules untouched. Remove these copies on exit; installed files remain in
# install_root.
source_dir=$(mktemp -d "$sdk_root/source.XXXXXX")
trap 'rm -rf -- "$source_dir"' EXIT HUP INT TERM

for dependency in ps2sdk ps2sdk-ports
do
    mkdir "$source_dir/$dependency"
    git -C "$repo_root/third_party/$dependency" archive \
        --format=tar --output="$source_dir/source.tar" HEAD
    tar -xf "$source_dir/source.tar" -C "$source_dir/$dependency"
done

export PS2SDK="$install_root/ps2sdk"
export GSKIT="$install_root/gsKit"
export PS2SDKSRC="$source_dir/ps2sdk"
sdk_bin_path="$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin:$PS2DEV/dvp/bin:$PS2SDK/bin"
export PATH="$sdk_bin_path:$PATH"

# The SDK owns dependency fetching and version selection. Run its unmodified
# script before patching; don't let a second fetch reset patched lwIP sources.
(
    cd "$PS2SDKSRC"
    bash ./download_dependencies.sh
)

patch -d "$PS2SDKSRC" -p1 --batch --forward \
    -i "$repo_root/patches/ps2sdk/receive-pool.patch"

patch -d "$PS2SDKSRC" -p1 --batch --forward \
    -i "$repo_root/patches/ps2sdk/audsrv-refill-threshold.patch"

patch -d "$PS2SDKSRC" -p1 --batch --forward \
    -i "$repo_root/patches/ps2sdk/audsrv-cleanup.patch"

if [ "$variant" = diagnostic ]
then
    patch -d "$PS2SDKSRC" -p1 --batch --forward -i "$repo_root/patches/ps2sdk/network-diagnostic.patch"

    diagnostic_include="$PS2SDKSRC/iop/tcpip/tcpip-base/include"
    diagnostic_source="$repo_root/src/common/platform/network/diagnostic"

    node "$repo_root/tools/contracts/generate.mjs" "$diagnostic_include/contracts"
    cp "$diagnostic_source/wire.h" "$diagnostic_include/stroom_diagnostic_wire.h"
    cp "$diagnostic_source/hooks.h" "$diagnostic_include/stroom_diagnostic_hooks.h"
    cp "$diagnostic_source/iop.c" \
        "$PS2SDKSRC/iop/tcpip/tcpip-base/stroom_diagnostic.c"
fi

# Build and install the complete SDK using its upstream targets.
make -C "$PS2SDKSRC" -o download_dependencies install

# Ports creates SDK-relative links to the official toolchain files.
ln -sfn "$PS2DEV/share" "$install_root/share"

# Keep upstream versions and recipes; select only the player libraries.
patch -d "$source_dir/ps2sdk-ports" -p1 --batch --forward \
    -i "$repo_root/patches/ps2sdk-ports/select-libraries.patch"

make -C "$source_dir/ps2sdk-ports" cmakelibs \
    PORTS_LIBRARIES="zlib libpng libjpeg-turbo gsKit"

# Save the installed environment for later builds. PS2SDKSRC is deliberately
# omitted because the temporary source directory is removed when we exit.
cat > "$install_root/environment.sh" <<EOF
# Generated by tools/sdk/build.sh.
export PS2DEV="$PS2DEV"
export PS2SDK="$PS2SDK"
export GSKIT="$GSKIT"
export PATH="$sdk_bin_path:\$PATH"
EOF

touch "$built_marker"
printf 'Built %s SDK: %s\n' "$variant" "$install_root"
