#pragma once

#include "ui/shared/player_layout.h"
#include "ui/shared/font.h"

#define UI_PLAYER_COVER_METER_GAP 16.0f
#define UI_PLAYER_COVER_LEFT      (UI_SAFE_LEFT + UI_METER_WIDTH + UI_PLAYER_COVER_METER_GAP)
#define UI_TRACK_PANEL_TOP        (UI_FOOTER_TOP * DISPLAY_HEIGHT / UI_REFERENCE_HEIGHT + UI_PANEL_BORDER_HEIGHT)
#define UI_PLAYER_COVER_SIDE      128

/* One third of the cover overlaps the visualizer, clear of the left meter. */
#define UI_PLAYER_COVER_OVERLAP (UI_PLAYER_COVER_SIDE / 3.0f)
#define UI_PLAYER_COVER_TOP     (UI_TRACK_PANEL_TOP - UI_PLAYER_COVER_OVERLAP)

#define UI_TRACK_METADATA_GAP      24.0f
#define UI_TRACK_METADATA_LEFT     (UI_PLAYER_COVER_LEFT + UI_PLAYER_COVER_SIDE + UI_TRACK_METADATA_GAP)
#define UI_TRACK_METADATA_ROW_STEP 24.0f
#define UI_TRACK_METADATA_TOP      (UI_PLAYER_COVER_TOP + UI_PLAYER_COVER_SIDE - 2 * UI_TRACK_METADATA_ROW_STEP - UI_TEXT_HEIGHT * UI_PLAYER_TEXT_SCALE)
